Traceback (most recent call last):
  File "/data/data/com.termux/files/home/cloud-api/bot.py", line 14, in <module>
    bot = Bot(token=TELEGRAM_TOKEN)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiogram/client/bot.py", line 273, in __init__
    validate_token(token)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiogram/utils/token.py", line 27, in validate_token
    raise TokenValidationError("Token is invalid!")
aiogram.utils.token.TokenValidationError: Token is invalid!
